version: "3.6"
services:
    webserver:
        image: nginx:alpine
        depends_on:
            - "php"
        volumes:
            - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./public:/var/www/html/public
        ports:
            - "8000:80"
    php:
        build: ./.docker/php
        volumes:
            - ./.docker/php/php.ini:/etc/php7/php.ini
            - .:/var/www/html
    db:
        image: mysql:8.0.21
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=test
